spring:
  application:
    name: gigker
  jpa:
    hibernate:
      ddl-auto: create-drop  # ??? ?? ??
    show-sql: true      # SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
    database: mysql   # ?? ?? ??
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gigkerdev?allowPublicKeyRetrieval=true&characterEncoding=UTF-8 # ????, ?????
    username: ${MYSQL_NAME} #root # ????? ?????.
    password: ${MYSQL_SECRET} #?? mysql ??? ??? ????

server:
  servlet:
    encoding:
      force-response: true
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:localhost.p12      #HTTPS SETTING
#    key-password: changeit

mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY} #???? ??
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

# ??
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG